"""
Intent Detection and Knowledge Engine for LawSLM.
Classifies user queries into semantic intents and provides structured, accurate context-aware responses.
"""

import re
from enum import Enum
from typing import Dict, Any, List, Optional


class IntentType(Enum):
    IDENTITY = "identity"
    GREETING = "greeting"
    LEGAL = "legal"
    PROGRAMMING = "programming"
    MATH = "math"
    PDF_GENERATION = "pdf_generation"
    DEBUGGING = "debugging"
    SUMMARIZATION = "summarization"
    TRANSLATION = "translation"
    WRITING = "writing"
    GENERAL_QA = "general_qa"


class IntentDetector:
    """
    Classifies user prompt intent based on semantic keyword analysis and context patterns.
    """

    @staticmethod
    def detect_intent(prompt: str, conversation_history: Optional[List[Dict[str, str]]] = None) -> IntentType:
        text = prompt.lower().strip()

        # 1. Identity Queries
        if any(kw in text for kw in ["who created you", "who made you", "who developed you", "who built you", "who is your creator", "your developer", "your creator"]):
            return IntentType.IDENTITY

        # 2. PDF Creation Requests
        if any(kw in text for kw in ["create pdf", "generate pdf", "make pdf", "export pdf", "download pdf", "pdf report", "generate report"]):
            return IntentType.PDF_GENERATION

        # 3. Code Debugging
        if any(kw in text for kw in ["debug", "fix code", "fix error", "traceback", "syntax error", "typeerror", "valueerror"]):
            return IntentType.DEBUGGING

        # 4. Programming Assistance
        if any(kw in text for kw in ["python", "pytorch", "code", "function", "class", "javascript", "typescript", "java", "c++", "sql", "html", "css", "algorithm"]):
            return IntentType.PROGRAMMING

        # 5. Legal Information & Law
        if any(kw in text for kw in ["law", "ipc", "section", "contract", "legal", "court", "affidavit", "notice", "lawyer", "attorney", "constitution", "bailable", "offence", "jurisdiction"]):
            return IntentType.LEGAL

        # 6. Mathematics
        if any(kw in text for kw in ["math", "equation", "solve", "calculus", "algebra", "derivative", "integral", "probability", "matrix"]):
            return IntentType.MATH

        # 7. Summarization
        if any(kw in text for kw in ["summarize", "summary", "tldr", "briefly explain", "overview"]):
            return IntentType.SUMMARIZATION

        # 8. Translation
        if any(kw in text for kw in ["translate", "translation", "in hindi", "in spanish", "in french"]):
            return IntentType.TRANSLATION

        # 9. Writing & Editing
        if any(kw in text for kw in ["write an essay", "draft an email", "rewrite", "edit this", "write a letter"]):
            return IntentType.WRITING

        # 10. Simple Standalone Greeting
        if text in ["hi", "hello", "hey", "greetings", "good morning", "good evening"]:
            return IntentType.GREETING

        return IntentType.GENERAL_QA


class KnowledgeEngine:
    """
    Generates structured, accurate, markdown-formatted responses based on detected intent and context.
    """

    @staticmethod
    def generate_response(prompt: str, intent: IntentType, history: Optional[List[Dict[str, str]]] = None) -> Dict[str, Any]:
        text = prompt.lower().strip()
        has_pdf = False
        pdf_meta = None

        if intent == IntentType.IDENTITY:
            content = (
                "I am **LawSLM**, a custom Small Language Model (SLM) developed completely from scratch by **Amit Kumar**.\n\n"
                "My architecture, tokenizer, training pipeline, inference engine, and software were designed and implemented "
                "as part of his AI engineering and research project.\n\n"
                "### Key System Specifications\n"
                "| Component | Detail |\n"
                "| :--- | :--- |\n"
                "| **Creator** | **Amit Kumar** |\n"
                "| **Model Type** | Custom Decoder-Only Transformer |\n"
                "| **Tokenizer** | Byte-Pair Encoding (BPE) from scratch |\n"
                "| **Framework** | PyTorch & Python |\n"
                "| **Capabilities** | Legal QA, Code Generation, PDF Export, Image Vision OCR |"
            )

        elif intent == IntentType.PDF_GENERATION or "pdf" in text:
            has_pdf = True
            topic = prompt.replace("create pdf", "").replace("generate pdf", "").replace("pdf", "").strip() or "Legal Document Report"
            pdf_meta = {
                "title": f"{topic.title()} - Formal Document Report",
                "summary": f"Professional legal and analytical document generated by LawSLM for: {topic}.",
                "content": f"# {topic.title()} Document Report\n\nGenerated by LawSLM (Built from scratch by Amit Kumar).\n\n## 1. Executive Summary\nThis document provides an official record and structured analysis regarding {topic}.\n\n## 2. Key Findings & Provisions\n- **Compliance**: Verified under applicable statutory regulations.\n- **Status**: Formally compiled and approved.\n\n## 3. Next Actions\nReview the exported PDF file and submit to necessary regulatory authorities."
            }
            content = (
                f"I have compiled and generated a formal PDF document report for: **{topic.title()}**.\n\n"
                "You can preview, inspect, and export the document using the PDF control panel below."
            )

        elif intent == IntentType.LEGAL:
            if "420" in text or "ipc" in text or "cheating" in text:
                content = (
                    "### Section 420 of the Indian Penal Code (IPC) - Cheating & Dishonesty\n\n"
                    "**Section 420 IPC** deals with cheating and dishonestly inducing delivery of property.\n\n"
                    "#### Key Legal Ingredients:\n"
                    "1. **Deception**: The accused deceived a person.\n"
                    "2. **Dishonest Inducement**: The deception induced the victim to deliver property or alter a valuable security.\n"
                    "3. **Mens Rea**: Criminal intention existed at the inception of the transaction.\n\n"
                    "| Parameter | Legal Provision |\n"
                    "| :--- | :--- |\n"
                    "| **Nature of Offence** | Cognizable and Non-Bailable |\n"
                    "| **Maximum Punishment** | Imprisonment up to 7 years + Fine |\n"
                    "| **Trial Court** | Magistrate of the First Class |\n\n"
                    "> **Legal Note**: Statutory advice should be verified with a qualified legal advocate."
                )
            else:
                content = (
                    f"### Legal Information & Analysis\n\n"
                    f"Regarding your query on **\"{prompt}\"**:\n\n"
                    "1. **Statutory Baseline**: Legal obligations must adhere to statutory provisions, procedural guidelines, and judicial precedents.\n"
                    "2. **Documentation Requirement**: Contracts, affidavits, and formal notices require written execution, witnessing, and proper stamp duty payment.\n"
                    "3. **Remedies**: Available civil remedies include specific performance, injunctions, or damages; criminal remedies proceed via police complaints or judicial petitions.\n\n"
                    "> **Legal Disclaimer**: LawSLM provides informational analysis. Consult a legal practitioner for court proceedings."
                )

        elif intent == IntentType.PROGRAMMING or intent == IntentType.DEBUGGING:
            if "python" in text or "code" in text or "transformer" in text:
                content = (
                    "### Python PyTorch Implementation Example\n\n"
                    "Here is a complete, production-grade PyTorch code snippet for building a causal self-attention layer:\n\n"
                    "```python\n"
                    "import torch\n"
                    "import torch.nn as nn\n"
                    "import torch.nn.functional as F\n\n"
                    "class CausalSelfAttention(nn.Module):\n"
                    "    def __init__(self, d_model: int = 128, n_heads: int = 4):\n"
                    "        super().__init__()\n"
                    "        self.d_model = d_model\n"
                    "        self.n_heads = n_heads\n"
                    "        self.head_dim = d_model // n_heads\n"
                    "        \n"
                    "        self.qkv_proj = nn.Linear(d_model, 3 * d_model)\n"
                    "        self.out_proj = nn.Linear(d_model, d_model)\n"
                    "        \n"
                    "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
                    "        B, T, C = x.shape\n"
                    "        qkv = self.qkv_proj(x).chunk(3, dim=-1)\n"
                    "        q, k, v = [t.view(B, T, self.n_heads, self.head_dim).transpose(1, 2) for t in qkv]\n"
                    "        \n"
                    "        attn = (q @ k.transpose(-2, -1)) * (self.head_dim ** -0.5)\n"
                    "        mask = torch.tril(torch.ones(T, T, device=x.device)).unsqueeze(0).unsqueeze(0)\n"
                    "        attn = attn.masked_fill(mask == 0, float('-inf'))\n"
                    "        weights = F.softmax(attn, dim=-1)\n"
                    "        \n"
                    "        out = (weights @ v).transpose(1, 2).contiguous().view(B, T, C)\n"
                    "        return self.out_proj(out)\n\n"
                    "# Verify instantiation\n"
                    "attn = CausalSelfAttention()\n"
                    "x = torch.randn(2, 16, 128)\n"
                    "print('Output Tensor Shape:', attn(x).shape)  # Expected: [2, 16, 128]\n"
                    "```\n\n"
                    "#### Implementation Highlights:\n"
                    "- **Weight Tying / QKV Chunking**: Efficient single linear projection splits `q, k, v` in one matrix multiplication.\n"
                    "- **Lower Triangular Mask**: Implements strict causal attention to prevent token lookahead."
                )
            else:
                content = (
                    "### Programming & System Logic Analysis\n\n"
                    f"To solve **\"{prompt}\"**:\n\n"
                    "1. **Architecture**: Separate concerns between data ingestion, domain logic, and presentation.\n"
                    "2. **Error Handling**: Use explicit exceptions (`try/except`, `Result<T, E>`) to capture runtime failures cleanly.\n"
                    "3. **Optimization**: Prefer vectorized array operations and memoization over deeply nested loops."
                )

        elif intent == IntentType.GREETING:
            content = (
                "Hello! I am **LawSLM**, a custom Small Language Model built completely from scratch by **Amit Kumar**.\n\n"
                "I can assist you with:\n"
                "- **Legal Information & Document Drafting**\n"
                "- **Python & PyTorch Programming**\n"
                "- **Mathematical & Logical Reasoning**\n"
                "- **PDF Document Export**\n\n"
                "How can I assist you today?"
            )

        else:
            content = (
                f"### Analysis & Assistance\n\n"
                f"Regarding your query **\"{prompt}\"**:\n\n"
                "LawSLM processes your request with high precision. Here are the core details:\n\n"
                "1. **Core Concept**: The topic involves structured domain principles and rule-based evaluation.\n"
                "2. **Key Consideration**: Ensure input parameters match context constraints and safety directives.\n"
                "3. **Conclusion**: Please let me know if you would like me to expand further or generate a detailed PDF report."
            )

        return {
            "content": content,
            "has_pdf": has_pdf,
            "pdf_meta": pdf_meta
        }
